language: java

jdk:
  - openjdk8

# To increase the memory size available during Travis build.
sudo: required

env:
  global:
    # https://docs.travis-ci.com/user/environment-variables/#Encrypting-environment-variables
    # Encrypted `GCS_SECRET` variable.
    - secure: "aSu4WatRfyjgkt3GIhEIbsfsXmdaPppXuAD6NeO2qwr/dG/JXQh/GImJT8wXz5jrQiUL7UldimICiVwEpgl4p6hmbyAbCII7YnMjOWv+rGdKSnod/xsz5iWqlncY3dIzv+sZ7ZvkmjNzMlxvcp8t3eTlxA7LZxO07hCALh+uE9JjdFnj4Xxtm53SAJvnsvbhp/f+W6iEo4nQO0V6cn2LokpmL/E9cl0varztGRNcv/r+EgAuRFPFZO92/tFv8o2d+QNuitJfqRAi7lzTNC7/nPWBx5U0TgCnRCxVm0i3+aRGRw6JZPTgTV95gXVgb11b/aOn1WF0+ocjuC/p5HGB0bBAIADtFY5ud+9tgAlFvFrxn0g/O5qMM3URugXuUAgK31tyGuxtAbG/AU5bebfRiJcYYWiJVNCouJTGlM+WbxHXFO+1ZiSmxHKAHit2nTeeYqPDUGmnCHcDqRvn9CydRMd8bJJ0Htl8try99KQ0dPOVx+Tm8M2M2idfSbYbXe2kM6Cm1IiZWsZJ4vtRHK2XARSM06l7Ptpls1Xi6FWwxmU46hSQ1lVV8s4Bc6Kk8Cnq80rFSKnwXbZKQksOUdLyZpalTXMSMivxBR14PEUK33ZXfO5Ei6GXY6puxfrjmi9Lp0ehehbfElSCANQAmYCbjHgcwvmQICEFUEG2dz4hjLc="

install:
  - chmod +x gradlew
  - chmod +x config/scripts/register-ssh-key.sh

script:
  - ./gradlew check --stacktrace

  # Decrypt and unarchive Maven and Google Cloud Storage credentials.
  - openssl aes-256-cbc -K $encrypted_7ba7f7c5898b_key -iv $encrypted_7ba7f7c5898b_iv -in credentials.tar.enc -out credentials.tar -d
  - tar xvf credentials.tar
  - chmod 600 deploy_key_rsa

after_success:
  # See: https://github.com/codecov/example-java/blob/master/.travis.yml
  - bash <(curl -s https://codecov.io/bash)
  - |
    if [[ $TRAVIS_BRANCH == master ]] && [[ $TRAVIS_PULL_REQUEST == false ]]; then
      chmod +x ./config/scripts/trigger-publishing.sh
      sh ./config/scripts/trigger-publishing.sh
    fi

after_script:
  - chmod +x ./config/scripts/upload-artifacts.sh
  - ./config/scripts/upload-artifacts.sh
