language: java

# To increase the memory size available during Travis build.
sudo: required

env:
  global:
    # Encrypted `CODACY_PROJECT_TOKEN` variable according to:
    # https://docs.travis-ci.com/user/environment-variables/#Encrypting-environment-variables
    - secure: W9oO7972ko1q4EvFaxZkcAdFU1SxQRjHpF8qSrohH48ZmPrUrNdJj6urp1roSLD6ic/o61SOAVwRLbSTW9zO7faCImzrAgnHXN+ogslsiJp1qH95RSrI7AglDkJOTaoNeTnKXuhiEBBORmkK0nM2pu6ADPkpHZNXCCbBRfZw11lMFB1ju8VeGK8xcET7yZBLD2HXXGwDIq80KE1twRMUOge9SMlMihwv75XsTKyDAL/NyaWgr6OjCwKwH+0qjc3q6LtxEMa4781XpHKpvls0WdiHH9BSmmcktLqKf3d9QRFRGUqdrO6DgoAKQqqS92SIckbqSniaOI/beOEycjU9/zSlxx2VheJ7aXFgAdsHVMAw1yDq+UHmEXWr54HP5JtyHDpaHy1sL0a03Hhdkkf0vK+YBn/NCsLgDeMQQ2P5gzY6HrvkesO63ab+edJHYF4GT9YYyx7opyakWFt0QllwMYLBJsMk2KEeKxphZYbM+6/FNF1HeUK435K0yOWS3X5eXj2JkkJ6W/sTmyPg9Xw4FmCEvpCsZf/blpVMrGC0Y+I6+1cVu1le69cMBh667qF8pZ6/eW0S3hgnxrR5UrGPLqHlOr4eNG2aiUbl33NzoyiY4UYSCHJ4C/wIx9mWJjxi/hyfEZhT/TaD1b58TUHR3SN2QF3+fB5pCWPT3eV1ESw=
    # Encrypted `GCS_SECRET` variable.
    - secure: CquzdOi8ZfScxnfaXIHasd5OxO2zqAoL0dES3g8AA5HPv59kLrwm+mXAIMijsk2OrIDG0v+UY+hwMi1SdjC0tvfrXr+Ks2e18BrQ5OKAROJtzSyr9UJD+UbOa2ukNHE/3qRJH3mL7qTZjPEcbnekzHga8h/O7EEJFWPn671YGPBy+asnkCX/vP5Qa5SuICJqvNiS64GbgLBPsBsQK36nTgQAfW6iLHTQSNP1rbDTUfNqkgNXEiPyKcx1q37W0qQYaVpPsKgndSVif55eO4tgOyZCrD5R8avxsSEcWIRh0TFv480f+iihGCFKwOiE/ZTHXLykDoFKmyGqipmzdSfsvEjMFTPJGOr1BTNIKz9mtMRtiDVjR5C1StzIYlo+nUlmfyir/OADw6Ae7kbbVGon10IvmgfJ9lrNG9C3xcVHcidEGR/hICy1p5BwLz1lJDrxfd3ej6+EuxB+L5UhiiswueH1Ju6EHCxIZIxrbPSDHhxlex0V93Flv6zuKUeLtsfrU7HpSUjyqD3EQav0+Z49zIA+Iss5+P+5FBpcFDdheqYt/hRf8Yu4CYuVsFjaH1y1MKMIWaQ+1mF7h3f6Lm+6N7N0FUgU7AWfitpIA7tnXs+GMqaVrAKQy2ypeB9eU66AVg181L0hEXLQ5ti0Hcq+n43YfgbkC1Zh0fQIrfuOKnk=

before_install:
  - chmod +x gradlew

script:
  - ./gradlew check --stacktrace

  # Decrypt and unarchive Maven and Google Cloud Storage credentials.
  - openssl aes-256-cbc -K $encrypted_514b32ab8781_key -iv $encrypted_514b32ab8781_iv -in credentials.tar.enc -out credentials.tar -d
  - tar xvf credentials.tar

  - ./gradlew cleanGCS --info

  # The publishing script should be executed in `script` section in order to
  # fail the Travis build if execution of this script is failed.
  - chmod +x ./scripts/publish-artifacts.sh
  - ./scripts/publish-artifacts.sh

after_success:
  # See: https://github.com/codecov/example-java/blob/master/.travis.yml
  - bash <(curl -s https://codecov.io/bash)
  - chmod +x ./scripts/report-coverage.sh
  - ./scripts/report-coverage.sh

after_script:
  - chmod +x ./scripts/upload-artifacts.sh
  - ./scripts/upload-artifacts.sh
